name: Scheduled Workflow

on:
  schedule:
    - cron: '0 3 * * *'   # Runs every day at 3:00 AM (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "This runs on schedule!"
